<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>GoodHamburger.Tests</RootNamespace>
    <AssemblyName>GoodHamburger.Tests</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.14" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\GoodHamburger.Domain\GoodHamburger.Domain.csproj" />
    <ProjectReference Include="..\..\src\GoodHamburger.API\GoodHamburger.API.csproj" />
  </ItemGroup>
</Project>